AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Function
      Description: !Sub
        - Stack ${StackTagName} Environment ${EnvironmentTagName} Function ${ResourceName}
        - ResourceName: Function
      CodeUri: src
      Handler: index.handler
      Runtime: nodejs10.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
  wssblog:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Description: !Sub
        - ${ResourceName} From Stack ${StackTagName} Environment ${EnvironmentTagName}
        - ResourceName: wssblog
      Name: !Sub
        - ${StackTagName}-${EnvironmentTagName}-${ResourceName}
        - ResourceName: wssblog
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
  wssblogDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref wssblog
    DependsOn:
      - wssblogRoutetest
  wssblogStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref wssblog
      StageName: !Ref EnvironmentAPIGatewayStageName
      DeploymentId: !Ref wssblogDeployment
  wssblogRoutetestIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref wssblog
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Function.Arn}/invocations
  wssblogRoutetestIntegrationResponse:
    Type: AWS::ApiGatewayV2::IntegrationResponse
    Properties:
      ApiId: !Ref wssblog
      IntegrationId: !Ref wssblogRoutetestIntegration
      IntegrationResponseKey: $default
  wssblogRoutetestIntegrationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Function
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:${wssblog}/*/test
  wssblogRoutetest:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref wssblog
      RouteKey: test
      Target: !Sub integrations/${wssblogRoutetestIntegration}
      OperationName: echo-value
  wssblogRoutetestResponse:
    Type: AWS::ApiGatewayV2::RouteResponse
    Properties:
      ApiId: !Ref wssblog
      RouteId: !Ref wssblogRoutetest
      RouteResponseKey: $default
Parameters:
  StackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  EnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  EnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (injected by Stackery at deployment time)